// Command generate-output creates Go output models and Markdown reference docs.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type schema struct {
	Title, Description string
	Type               string
	Required           []string
	Properties         map[string]*schema
	Defs               map[string]*schema `json:"$defs"`
	Ref                string             `json:"$ref"`
	Items              *schema
	Enum               []string
	Examples           []any
}

func main() {
	b, err := os.ReadFile("schemas/search.schema.json")
	if err != nil {
		panic(err)
	}
	var root schema
	if err := json.Unmarshal(b, &root); err != nil {
		panic(err)
	}
	var goText strings.Builder
	goText.WriteString("// Code generated by go run ./tools/generate-output; DO NOT EDIT.\n\n")
	goText.WriteString("package output\n\n")
	goText.WriteString(emitStruct(root.Title, &root))
	names := make([]string, 0, len(root.Defs))
	for n := range root.Defs {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		goText.WriteString(emitStruct(n, root.Defs[n]))
	}
	formatted, err := format.Source([]byte(goText.String()))
	if err != nil {
		panic(err)
	}
	write("internal/output/search.gen.go", string(formatted))

	var md strings.Builder
	md.WriteString("<!-- Generated by go run ./tools/generate-output; DO NOT EDIT. -->\n\n")
	fmt.Fprintf(&md, "# `search` JSON output\n\n%s\n\n", root.Description)
	emitDocs(&md, root.Title, &root, root.Defs)
	for _, n := range names {
		emitDocs(&md, n, root.Defs[n], root.Defs)
	}
	md.WriteString("## Examples\n\nThese synthetic examples are validated against the schema.\n\n")
	for _, example := range root.Examples {
		encoded, err := json.MarshalIndent(example, "", "  ")
		if err != nil {
			panic(err)
		}
		fmt.Fprintf(&md, "```json\n%s\n```\n\n", encoded)
	}
	write("docs/reference/search-output.md", strings.TrimSpace(md.String())+"\n")
}

func emitStruct(name string, s *schema) string {
	required := set(s.Required)
	keys := orderedKeys(s.Properties)
	var b strings.Builder
	fmt.Fprintf(&b, "// %s %s\ntype %s struct {\n", name, s.Description, name)
	for _, k := range keys {
		p := s.Properties[k]
		tag := k
		if !required[k] {
			tag += ",omitempty"
		}
		fmt.Fprintf(&b, "\t%s %s `json:\"%s\"`\n", goName(k), goType(p), tag)
	}
	b.WriteString("}\n\n")
	return b.String()
}

func emitDocs(b *strings.Builder, name string, s *schema, defs map[string]*schema) {
	fmt.Fprintf(b, "## %s\n\n| Field | Type | Required | Description |\n|---|---|---:|---|\n", name)
	required := set(s.Required)
	for _, k := range orderedKeys(s.Properties) {
		p := s.Properties[k]
		typeName := docType(p)
		if len(p.Enum) > 0 {
			typeName += " (`" + strings.Join(p.Enum, "`, `") + "`)"
		}
		fmt.Fprintf(b, "| `%s` | %s | %t | %s |\n", k, typeName, required[k], p.Description)
	}
	b.WriteString("\n")
}

func goType(s *schema) string {
	if s.Ref != "" {
		return strings.TrimPrefix(s.Ref, "#/$defs/")
	}
	switch s.Type {
	case "integer":
		return "int"
	case "array":
		return "[]" + goType(s.Items)
	default:
		return "string"
	}
}

func docType(s *schema) string {
	if s.Ref != "" {
		name := strings.TrimPrefix(s.Ref, "#/$defs/")
		return "[`" + name + "`](#" + strings.ToLower(name) + ")"
	}
	if s.Type == "array" {
		return "array of " + docType(s.Items)
	}
	return s.Type
}

func goName(v string) string {
	initialisms := map[string]string{"id": "ID", "url": "URL"}
	var b strings.Builder
	for word := range strings.SplitSeq(v, "_") {
		if known := initialisms[word]; known != "" {
			b.WriteString(known)
			continue
		}
		runes := []rune(word)
		if len(runes) > 0 {
			runes[0] = unicode.ToUpper(runes[0])
		}
		b.WriteString(string(runes))
	}
	return b.String()
}

func set(xs []string) map[string]bool {
	m := map[string]bool{}
	for _, x := range xs {
		m[x] = true
	}
	return m
}

func orderedKeys(m map[string]*schema) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func write(path, value string) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(path, []byte(value), 0o644); err != nil {
		panic(err)
	}
}
