// Code generated by go run ./tools/generate-output; DO NOT EDIT.

package output

// SearchOutput The JSON document produced by the search command after collection starts.
type SearchOutput struct {
	IncompleteReason string           `json:"incomplete_reason,omitempty"`
	PostCount        int              `json:"post_count"`
	ResourceCount    int              `json:"resource_count"`
	Resources        []Resource       `json:"resources"`
	RetrievedAt      string           `json:"retrieved_at"`
	Search           SearchConditions `json:"search"`
	Status           string           `json:"status"`
}

// Resource
type Resource struct {
	Sources []Source `json:"sources"`
	URL     string   `json:"url"`
}

// SearchConditions
type SearchConditions struct {
	EndTime   string `json:"end_time,omitempty"`
	Language  string `json:"language,omitempty"`
	Limit     int    `json:"limit"`
	Query     string `json:"query"`
	StartTime string `json:"start_time,omitempty"`
}

// Source
type Source struct {
	CreatedAt string `json:"created_at"`
	PostID    string `json:"post_id"`
	PostURL   string `json:"post_url"`
	ShortURL  string `json:"short_url"`
	Text      string `json:"text"`
}
